[mypy]

[mypy-easyocr]
ignore_missing_imports = True

[mypy-easyocr.*]
ignore_missing_imports = True

[mypy-extract_msg]
ignore_missing_imports = True

[mypy-extract_msg.*]
ignore_missing_imports = True

[mypy-faiss]
ignore_missing_imports = True

[mypy-faiss.*]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True

[mypy-pypdfium2]
ignore_missing_imports = True

[mypy-pypdfium2.*]
ignore_missing_imports = True

[mypy-pytesseract]
ignore_missing_imports = True

[mypy-pytesseract.*]
ignore_missing_imports = True
